### ISSUE TITLE
About compressed H24 

### ISSUE THREAD

**Issue by DeepDevIA** [sevkel/BA#1]
Hello sevkel have you tried to reproduce the compressed of H24?
I have some difficulty doing it.
THANKS

**Comment by sevkel** [comment]
Hello DeepDevIA,

please be a bit more specific, what does your problem/question refer to when you ask for the compressed H24?

**Comment by DeepDevIA** [comment]
Thank you for answering
To reproduce the example used by DM21 Compressed chain of hydrogen atoms , I used the Newton method (it is a little slower but more precise). the SCF energy obtained with PBE is -8.883551250, but when I use the DM21 method (as it is described on the DM21 website at the best practice) an error occurs saying that there is no mol, I believe that it is Same problem when trying to calculate UV or IR.
Have you try to do this ?
Best

**Comment by sevkel** [comment]
Now i got you,

unfortunately no, i havent tried to reproduce these results. Sorry that i cant help you out with that problem. But you can try to open an issue at their repo, im sure they can help you out with your problem.

**Comment by DeepDevIA** [comment]
thank you sevkel
